SELECT *
FROM (
SELECT 'Address' AS table_name, 'AddressLine2' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [AddressLine2] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [AddressLine2] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[Address] UNION ALL
SELECT 'Address' AS table_name, 'SpatialLocation' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [SpatialLocation] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [SpatialLocation] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[Address] UNION ALL
SELECT 'Customer' AS table_name, 'PersonID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [PersonID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [PersonID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[Customer] UNION ALL
SELECT 'Customer' AS table_name, 'StoreID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [StoreID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [StoreID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[Customer] UNION ALL
SELECT 'Customer' AS table_name, 'TerritoryID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [TerritoryID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [TerritoryID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[Customer] UNION ALL
SELECT 'EmailAddress' AS table_name, 'EmailAddress' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [EmailAddress] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [EmailAddress] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[EmailAddress] UNION ALL
SELECT 'Employee' AS table_name, 'OrganizationNode' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [OrganizationNode] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [OrganizationNode] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [HumanResources].[Employee] UNION ALL
SELECT 'Employee' AS table_name, 'OrganizationLevel' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [OrganizationLevel] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [OrganizationLevel] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [HumanResources].[Employee] UNION ALL
SELECT 'Person' AS table_name, 'Title' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Title] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Title] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[Person] UNION ALL
SELECT 'Person' AS table_name, 'MiddleName' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [MiddleName] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [MiddleName] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[Person] UNION ALL
SELECT 'Person' AS table_name, 'Suffix' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Suffix] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Suffix] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[Person] UNION ALL
SELECT 'Person' AS table_name, 'AdditionalContactInfo' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [AdditionalContactInfo] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [AdditionalContactInfo] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[Person] UNION ALL
SELECT 'Person' AS table_name, 'Demographics' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Demographics] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Demographics] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Person].[Person] UNION ALL
SELECT 'Product' AS table_name, 'Color' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Color] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Color] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'Size' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Size] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Size] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'SizeUnitMeasureCode' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [SizeUnitMeasureCode] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [SizeUnitMeasureCode] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'WeightUnitMeasureCode' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [WeightUnitMeasureCode] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [WeightUnitMeasureCode] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'Weight' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Weight] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Weight] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'ProductLine' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [ProductLine] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [ProductLine] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'Class' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Class] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Class] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'Style' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Style] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Style] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'ProductSubcategoryID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [ProductSubcategoryID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [ProductSubcategoryID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'ProductModelID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [ProductModelID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [ProductModelID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'SellEndDate' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [SellEndDate] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [SellEndDate] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'Product' AS table_name, 'DiscontinuedDate' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [DiscontinuedDate] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [DiscontinuedDate] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Production].[Product] UNION ALL
SELECT 'SalesOrderDetail' AS table_name, 'CarrierTrackingNumber' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [CarrierTrackingNumber] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [CarrierTrackingNumber] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderDetail] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'ShipDate' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [ShipDate] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [ShipDate] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'PurchaseOrderNumber' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [PurchaseOrderNumber] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [PurchaseOrderNumber] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'AccountNumber' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [AccountNumber] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [AccountNumber] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'SalesPersonID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [SalesPersonID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [SalesPersonID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'TerritoryID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [TerritoryID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [TerritoryID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'CreditCardID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [CreditCardID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [CreditCardID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'CreditCardApprovalCode' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [CreditCardApprovalCode] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [CreditCardApprovalCode] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'CurrencyRateID' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [CurrencyRateID] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [CurrencyRateID] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader] UNION ALL
SELECT 'SalesOrderHeader' AS table_name, 'Comment' AS column_name, COUNT(*) AS total_rows, SUM(CASE WHEN [Comment] IS NULL THEN 1 ELSE 0 END) AS null_count, ROUND(100.0 * SUM(CASE WHEN [Comment] IS NULL THEN 1 ELSE 0 END) / COUNT(*), 2) AS null_pct FROM [Sales].[SalesOrderHeader]) t
WHERE t.null_pct >= 5 AND t.null_pct <= 80;